server:
  port: 8888

encrypt:
  key-store:
    location: file://${user.home}/keystore/apiEncryptionKey.jks
    password: test1234
    alias: apiencryption

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

spring:
  application:
    name: bbl-config

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Backble/BBL-Config-Repo

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest