server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: bbl-config

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Backble/BBL-Config-Repo
